version: '3'

networks:
  default:
    external:
      name: kafka-network

services:
  admin:
    build: ./services/admin
    environment:
      KAFKA_BROKER_URL: broker:9092
  
  producer:
    build: ./services/producer
    environment:
      KAFKA_BROKER_URL: broker:9092
    depends_on: 
      - admin

  consumer:
    build: ./services/consumer
    environment:
      KAFKA_BROKER_URL: broker:9092
    depends_on: 
      - admin

