version: '3'

services:
  admin:
    build: ./services/admin
    environment:
      KAFKA_BROKER_URL: broker:9092
  
  producer:
    build: ./services/producer
    environment:
      KAFKA_BROKER_URL: broker:9092

  consumer:
    build: ./services/consumer
    environment:
      KAFKA_BROKER_URL: broker:9092

networks:
  default:
    external:
      name: kafka-network
